### ISSUE TITLE
Broken /pv recent player history texture

### ISSUE THREAD

**Issue by lineargraph** [jani270/FurfSky-Reborn-Dark#2]
![image](https://github.com/jani270/FurfSky-Reborn-Dark/assets/20768569/5bc17e61-793f-44fe-95fa-bffea442d252)

**Comment by jani270** [comment]
Fixed in https://github.com/jani270/FurfSky-Reborn-Dark/commit/cf01a75576d4df0a8cc4643201038536b5bf740a
